/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.26.2-g80f3030 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.26.2-g80f3030"
#endif
#define SDL_REVISION_NUMBER 0
